import React from "react";
import { Link } from "react-router-dom";

import Button from "@mui/material/Button";
import Divider from '@mui/material/Divider';
import Stack from '@mui/material/Stack';
import Chip from '@mui/material/Chip';
import Container from '@mui/material/Container';

import UploadFileIcon from '@mui/icons-material/UploadFile';
import DnsIcon from '@mui/icons-material/Dns';
import StorageIcon from "@mui/icons-material/Storage";

import List from "@mui/material/List";
import ListItemButton from '@mui/material/ListItemButton';
import ListItem from "@mui/material/ListItem";

import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";

export default function SelectAccountType(props) {
  return (
    <div className="layout dashboard mobile">
      <header className="layout_header">
        <Container className="layout_header_top_bar">
          <h2>I have an account</h2>
        </Container>
      </header>
      <main className="layout_content">
        <Container>
          <List
            subheader={
              <ListSubheader disableSticky={true}>Remote server</ListSubheader>
            }
          >
            <ListItemButton component={Link} to="/login">
              <ListItemIcon>
                <DnsIcon />
              </ListItemIcon>
              <ListItemText
                primary="Seven23"
                secondary={`Connect to the official Seven23.io instance`}
              />
            </ListItemButton>
            <ListItemButton component={Link} to="/server">
              <ListItemIcon>
                <StorageIcon />
              </ListItemIcon>
              <ListItemText
                primary="Change server"
                secondary={`Define your own backend instance to connect`}
              />
            </ListItemButton>
          </List>
          <List
            subheader={
              <ListSubheader disableSticky={true}>Offline</ListSubheader>
            }
          >
            <ListItemButton component={Link} to="/import-account">
              <ListItemIcon>
                <UploadFileIcon />
              </ListItemIcon>
              <ListItemText
                primary="Import .json file"
                secondary={`Import a .json file generated by the export feature of seven23`}
              />
            </ListItemButton>
          </List>
        </Container>
      </main>
      <footer className="layout_footer">
        <Container>
          <Stack direction='row' spacing={2} style={{ justifyContent: 'space-between'}}>
            
            <Link to="/" tabIndex="-1">
              <Button
                fullWidth
                color='inherit'
                variant="text"
              >
                Cancel
              </Button>
            </Link>
          </Stack>
        </Container>
      </footer>
    </div>
  );
}