name: "Build and Deploy"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install caniuse-lite --legacy-peer-deps
    - run: npm install --legacy-peer-deps
    - run: npm run build:no-progress --if-present
    - run: npx browserslist@latest --update-db
    - run: npm run test
    # - run: npm run e2e:cli
    - name: Run the backend process with Docker
      uses: addnab/docker-run-action@v3
      with:
          image: sebastienbarbier/seven23
          options: -p 8000:8000 -e ALLOW_ACCOUNT_CREATION='true'
          run: |
            while ! nc -z localhost 8000; do
              sleep 0.1 # wait for 1/10 of the second before check again
            done
    - name: Cypress install
      uses: cypress-io/github-action@v5.0.0 # use the explicit version number
      with:
        # Disable running of tests within install job
        install-command: npm install --legacy-peer-deps
        runTests: true
        start: npm run serve:build http://127.0.0.1:8080
        record: true
        config-file: ./cypress/config/cypress.production.config.js
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3.1.1
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3.1.1
      if: failure()
      with:
        name: cypress-videos
        path: cypress/videos
    - name: Update gh-pages
      if: github.ref == 'refs/heads/develop'
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: contact@sebastienbarbier.com
        build_dir: build
        cname: next.seven23.io
    - name: "Predeploy"
      if: github.ref == 'refs/heads/main'
      run: npm run predeploy
    - name: "Deploy with Swift"
      if: github.ref == 'refs/heads/main'
      env: # Set the secret as an input
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        OS_TENANT_ID: ${{ secrets.OS_TENANT_ID }}
        OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
      run: npm run deploy