name: "Build and Deploy"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.12.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --legacy-peer-deps
    - run: npm run build:no-progress --if-present
    - run: npx browserslist@latest --update-db
    - run: npm run test
    # - run: npm run e2e:cli
    - name: Cypress install
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          # Disable running of tests within install job
          runTests: true
          start: npm start
          record: true
          config-file: ./cypress/config/cypress.production.config.js
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: 63cf7a97-1159-4b34-89e9-5b842111177a
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update gh-pages
      if: github.ref == 'refs/heads/develop'
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: contact@sebastienbarbier.com
        build_dir: build
        cname: next.seven23.io
    - name: "Predeploy"
      if: github.ref == 'refs/heads/main'
      run: npm run predeploy
    - name: "Deploy with Swift"
      if: github.ref == 'refs/heads/main'
      env: # Set the secret as an input
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}
        OS_TENANT_ID: ${{ secrets.OS_TENANT_ID }}
        OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
      run: npm run deploy